# Generated by Django 4.2.6 on 2024-01-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('DESSERT', 'Dessert'), ('MAIN_COURSE', 'Main Course'), ('APPETIZER', 'Appetizer'), ('BEVERAGE', 'Beverage')], default='DESSERT', max_length=100),
        ),
    ]
